name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run basic app check
        run: |
          python -m py_compile app/app.py

      - name: Build Docker image
        run: |
          docker build -t devops-flask-app -f docker/Dockerfile .
    
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Login to ACR
        run: |
          az acr login --name devopsacrjack2026

      - name: Build and push Docker image
        run: |
          docker build -t devopsacrjack2026.azurecr.io/devops-flask-app:${{ github.sha }} -f docker/Dockerfile .
          docker push devopsacrjack2026.azurecr.io/devops-flask-app:${{ github.sha }}
